from pydantic import BaseModel
from typing import Optional, Any, List

class AgentState(BaseModel):
    '''Represents the shared state of the agent across multiple tool invocations and reasoning steps.
    This schema tracks both the current conversation context and intermediate data
    passed between chained tools (e.g., RAG → Email → PayPal). It provides a structured
    memory snapshot that can be updated as the agent performs reasoning or executes tools.
    Attributes:
        user_query (str): The latest query or instruction from the user.
        selected_tools (Optional[List[str]]): Tools chosen to handle the query.
        tool_outputs (Optional[List[Any]]): Outputs generated by executed tools.
        final_output (Optional[str]): The agent’s overall or synthesized response.
    '''
    user_query: str
    selected_tools: Optional[List[str]] = None
    tool_outputs: Optional[List[Any]] = None
    final_output: Optional[str] = None
